server:
  shutdown: graceful

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

spring:
  application:
    name: BUGDEMO
  lifecycle:
    timeout-per-shutdown-phase: 30s
  rabbitmq:
    host: localhost
    port: 5672
    username: bugdemouser
    password: bugdemouser
    virtual-host: bugdemo-vhost
